#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

nitrogen --restore &		# set wallpaper
xrdb ~/.config/X11/xresources & # uncomment to use Xresources colors/settings on startup
dunst &				# dunst for notifications
xset r rate 300 50 &		# Speed xrate up

exec dwm
#exec openbox-session
#exec icewm-session
#exec fvwm3
